services:
  basic-agent:
    image: capsule-agents
    ports:
      - "8001:9000"
    volumes:
      - ./agent.config.yaml:/app/agent.config.yaml
    environment:
      - AGENT_URL=http://localhost:8001
    restart: unless-stopped
    env_file:
      - .env
