name: PR Quality

on:
  pull_request:
    branches: [main, next]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [format, lint, check]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Run format check
        if: matrix.check == 'format'
        run: deno task fmt --check

      - name: Run lint check
        if: matrix.check == 'lint'
        run: deno task lint

      - name: Run type check
        if: matrix.check == 'check'
        run: deno task check
